# Operações

Há muitas operações com pandas que serão realmente úteis para você, mas não se enquadram em nenhuma categoria distinta. Vamos mostrar aqui nesta aula:

In [1]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Informação sobre valores exclusivos

In [2]:
df['col2'].unique()

array([444, 555, 666])

In [3]:
df['col2'].nunique()

3

In [4]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### Selecionando dados

In [5]:
# Selecione do DataFrame usando critérios de várias colunas
newdf = df[(df['col1']>1) & (df['col2']==444)]

In [11]:
newdf

   col1  col2 col3
3     4   444  xyz

### Aplicando funções

In [12]:
def times2(x):
    return x*2

In [16]:
df['col1']

0    1
1    2
2    3
3    4
Name: col1, dtype: int64

In [17]:
df['col1'].apply(times2)
#aplica a função a todoo dataframe

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [18]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [19]:
df['col1'].sum()

10

** Removendo colunas permanentemente **

In [20]:
del df['col1'].

** Obter nomes de coluna e índice: **

In [31]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [32]:
df.index

RangeIndex(start=0, stop=4, step=1)

** Ordenando um DataFrame **

In [33]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [34]:
df.sort_values(by='col2', ascending=False) #inplace=False por padrão
#ordena as linhas

   col2 col3
2   666  ghi
1   555  def
0   444  abc
3   444  xyz

** Encontre Valores Nulos ou Verifique Valores Nulos **

In [35]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

# Dados ausentes

Vamos mostrar alguns métodos convenientes para lidar com Missing Data em pandas:

In [48]:
import numpy as np

In [49]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [50]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [51]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [52]:
df.dropna(axis=1)
#remove a coluna - nao é muito comum

   C
0  1
1  2
2  3

In [53]:
df.dropna(thresh=2)
#indica o número de ausentes para que a linha ou coluna seja removida

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [54]:
df.fillna(value='Conteúdo')
df.fillna(value=0)
#substitui NaN por um valor específico

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [55]:
df['A'].fillna(value=df['A'].mean())
#Na coluna A está substituindo os NaN por uma média da propria coluna. Boa solução para alguns casos. Não todos.

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Reestrurando o dataframe

In [45]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [46]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [47]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN